language: csharp
mono: none
dotnet: 1.1.4
dist: trusty
install:
- bundle install
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bundle exec rake pull_request_job; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec rake merge_job; fi'