application_name: 'Liquor Cabinet API'

composition_root_project: 'LiquorCabinet.APIGatewayAdapter'

s3:
  secrets:
    bucket: application-and-service-secrets
    key: LiquorCabinetSettings.zip

environments:
  - name: 'production'
    variables:
      verbosity: 'Info'
    description: 'Live Production Environment.'
  - name: 'test'
    variables:
      verbosity: 'Debug'
    description: 'Generic Testing environment to test deployments and whatnot.'

lambdas:
  - lambda_name: 'LiquorCabinetService'
    handler: 'LiquorCabinet.APIGatewayAdapter::LiquorCabinet.APIGatewayAdapter.LambdaExecutor::ApiGatewayProxyInvocation'
    description: 'Backing Lambda for the Liquor Cabinet Application'
    timeout: 20
    memory_size: 1024
    role_arn: 'arn:aws:iam::235891526390:role/LambdaMicroservice'
    runtime: 'dotnetcore1.0'
    subnet_ids:
    - subnet-59e05e64
    - subnet-62b3a83b
    - subnet-22cadf09
    - subnet-e6b77790
    - subnet-3131b83d
    - subnet-5db9d938
    security_group_ids:
    - sg-46c5e920
    - sg-8e668dfb
    - sg-cf77adb6
    delete_unreferenced_versions: true
